### ISSUE TITLE
Code review / front end stack review

### ISSUE THREAD

**Issue by enmust** [geocollections/fossiilid.info#140]
2022 fossils app update.

We should make a small analysis in order to ease the development / update process

**Comment by Erikdzo** [comment]
## Code review

### Vuex store

- [ ] Store does not need to contain activeItem object. activeItem contains data that is currently visible to user on a page and is overwritten every time that user changes a page. 
- [ ] Similar to previous frontpage, route, items, lists, itemsPerPage, activeTab, errorMessage, process and page fields seem redundant.

### Server-side rendering

- [ ] Right now custom server side rendering is implemented, using vue-server-renderer, should consider using Nuxt.js.

### Meta data

- [ ] If Nuxt.js is implemented can use `head` property to set meta data and remove the custom solution that is implemented now.

### Components

- [ ] What is difference between TabGallery.vue and TabGallery_.vue?
- [ ] Unify component naming kebab-case to PascalCase
- [ ] VueFoldable is renamed in ItemPage to Foldable, component should not be renamed after import. Rename VueFoldable -> Foldable or something else. 

### Misc.

- [ ] Remove vim.exe.stacktrace
- [ ] static/js contains packages that could probably be added to package.json and removed from static/js
- [ ] util/customeDirectives.js is empty and should probably be deleted.
- [ ] util/filters.js does not seem to be used. Should delete.

## App review

### Header
- [ ] Search button icon should be changed.
- [ ] Region filter should probably be somewhere on the page, not in header. It is not exactly clear what it does.
- [ ] Could probably revamp the look of the header
- [ ] More list contains geocollections portal should probably switch to eMaapõu.

### Item view

- [ ] Font size is inconsitent. References are much larger than card titles and other texts.
- [ ] References should probably be paginated.
- [ ] Could we fit specimens table to overview tab? Or maybe move references and other tables to separate tabs?

### Frontpage
- [ ] Could current frontpage and advanced search page be combined?

### Advanced search
- [ ] Changing search result list page, creates a loading progression element that pushes the table below. This is distracting.
- [ ] Could the result list subheading be different tabs, so that the user could better understand what are the search results. Right now you have to scroll through a lot of pages to find a certain subheading.
- [ ] By default should show all results.

### Misc.

- [ ] Font
