### ISSUE TITLE
API: group by / distinct should work with multi_search

### ISSUE THREAD

**Issue by ollehints** [geocollections/fossiilid.info#30]
group by / distinct currently not removing duplicate records in multi_search.

**Comment by urtson** [comment]
Group by and distinct work separately, please provide an example query where they should work together

**Comment by ollehints** [comment]
They should not work together, but at least one of them should return desired result -- removing the duplicated, e.g., the following api call should return only one taxon: 
- https://api.geocollections.info/taxon/?paginate_by=10&fields=id,taxon,common_name__name,taxon&multi_search=value:mollu;fields:taxon,common_name__name;lookuptype:icontains&distinct=true

group_by gives right number of unique groups (1) but the individual 25 rows are of limited use:
- https://api.geocollections.info/taxon/?paginate_by=100&fields=id,taxon,common_name__name,taxon&multi_search=value:mollu;fields:taxon,common_name__name;lookuptype:icontains&group_by=id

thus, group_by works essentially differently than in SQL, where, "group by" and "distinct" are nearly identical in function and speed if user simply wants to remove duplicate rows from the result.

**Comment by urtson** [comment]
Well this is how Django works if you query related field from a table that has many linked records. Similar problem has appeared before. Btw, its not only multi_search issue.

Possible workaround is to query common names as related data:
https://api.geocollections.info/taxon/?paginate_by=10&fields=id,taxon&multi_search=value:mollu;fields:taxon,common_name__name;lookuptype:icontains&distinct=true&related_data=taxon_common_name&fields=name

Current code adds related data outside the object dictionary which is ok if you retrieve one record by id.
For multiple records as by filtering related data must be inside object dict otherwise it is useless. I rearranged the code a bit but it will break the current data handling in geokogud which must be then updated for rearranged data structure.

**Comment by ollehints** [comment]
mostly using solr index now
