### ISSUE TITLE
Allow selected images for species and genera

### ISSUE THREAD

**Issue by ollehints** [geocollections/fossiilid.info#85]
It would be useful to allow adding selected images for all taxonomic ranks, including genus and species. This would allow linking images to taxon pages that have no related specimen in the database. E.g., 
https://fossiilid.geokogud.info/32 shows to selected images and many automatic ones. 
https://fossiilid.geokogud.info/11084 should also show the same two images (correct data are returned by API).

**Comment by ollehints** [comment]
for some species images are not shown although they exist and are retrieved from API, e.g.; https://fossiilid.geokogud.info/15470. When asked via higher taxa images show up: https://fossiilid.geokogud.info/15469

should be investigated what is the problem -- or -- if going for one universal image showing function for all taxa, then that would solve the problem.

**Comment by OlesjaSenkiv** [comment]
> for some species images are not shown although they exist and are retrieved from API, e.g.; https://fossiilid.geokogud.info/15470. When asked via higher taxa images show up: https://fossiilid.geokogud.info/15469
> 
> should be investigated what is the problem -- or -- if going for one universal image showing function for all taxa, then that would solve the problem.

The problem is that both data retrieved from different sources this means different fields names are reterned
1. https://api.geocollections.info/taxon/?sql=get_taxon_images&keyword=1-29-38-93-338-341-15521-534-1070-1071-15469&page=1&paginate_by=20

2. https://api.geocollections.info/attachment/?specimen__specimenidentification__taxon__hierarchy_string__istartswith=1-29-38-93-338-341-15521-534-1070-1071-15469-15470&fields=id,specimen_id,specimen__specimen_id,specimen_image_id,database__acronym,uuid_filename,specimen__specimenidentification__taxon__id&format=json&distinct=true&order_by=stars
